INFO - 2022/06/22 00:20:01 -  End
INFO - 2022/06/22 00:50:01 -  End
INFO - 2022/06/22 01:20:01 -  End
INFO - 2022/06/22 01:50:01 -  End
INFO - 2022/06/22 02:20:01 -  End
INFO - 2022/06/22 02:50:01 -  End
INFO - 2022/06/22 03:20:01 -  End
INFO - 2022/06/22 03:50:01 -  End
INFO - 2022/06/22 04:20:01 -  End
INFO - 2022/06/22 04:50:01 -  End
INFO - 2022/06/22 05:20:01 -  End
INFO - 2022/06/22 05:50:01 -  End
INFO - 2022/06/22 06:20:01 -  End
INFO - 2022/06/22 06:50:01 -  End
INFO - 2022/06/22 07:20:01 -  End
INFO - 2022/06/22 07:50:01 -  End
INFO - 2022/06/22 08:20:01 -  End
INFO - 2022/06/22 08:50:01 -  End
INFO - 2022/06/22 09:20:01 -  End
INFO - 2022/06/22 09:50:01 -  End
INFO - 2022/06/22 10:20:01 -  End
INFO - 2022/06/22 10:50:01 -  End
INFO - 2022/06/22 11:20:01 -  End
INFO - 2022/06/22 11:50:01 -  End
INFO - 2022/06/22 12:20:01 -  End
INFO - 2022/06/22 12:50:01 -  End
INFO - 2022/06/22 13:20:01 -  End
INFO - 2022/06/22 13:50:01 -  End
INFO - 2022/06/22 14:20:01 -  End
INFO - 2022/06/22 14:50:01 -  End
INFO - 2022/06/22 15:20:01 -  End
INFO - 2022/06/22 15:50:02 -  End
INFO - 2022/06/22 16:20:01 -  End
INFO - 2022/06/22 16:50:00 -  End
INFO - 2022/06/22 17:20:00 -  End
INFO - 2022/06/22 17:50:00 -  End
INFO - 2022/06/22 18:20:00 -  End
INFO - 2022/06/22 18:50:00 -  End
INFO - 2022/06/22 19:20:00 -  End
INFO - 2022/06/22 19:50:00 -  End
Traceback (most recent call last):
  File "D:\StockPrediction\StockPrediction\\package\Step_1_CombineCSV.py", line 33, in <module>
    recordADF.to_csv(filePath+recordA, encoding='big5', index=False)
  File "C:\Users\Vivian\AppData\Roaming\Python\Python38\site-packages\pandas\core\generic.py", line 3170, in to_csv
    formatter.save()
  File "C:\Users\Vivian\AppData\Roaming\Python\Python38\site-packages\pandas\io\formats\csvs.py", line 185, in save
    f, handles = get_handle(
  File "C:\Users\Vivian\AppData\Roaming\Python\Python38\site-packages\pandas\io\common.py", line 493, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, errors=errors, newline="")
PermissionError: [Errno 13] Permission denied: './data/Step_0_ANN_Two_Result_ProcessA.csv'
Traceback (most recent call last):
  File "D:\StockPrediction\StockPrediction\\package\Step_1_CombineCSV.py", line 33, in <module>
    recordADF.to_csv(filePath+recordA, encoding='big5', index=False)
  File "C:\Users\Vivian\AppData\Roaming\Python\Python38\site-packages\pandas\core\generic.py", line 3170, in to_csv
    formatter.save()
  File "C:\Users\Vivian\AppData\Roaming\Python\Python38\site-packages\pandas\io\formats\csvs.py", line 185, in save
    f, handles = get_handle(
  File "C:\Users\Vivian\AppData\Roaming\Python\Python38\site-packages\pandas\io\common.py", line 493, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, errors=errors, newline="")
PermissionError: [Errno 13] Permission denied: './data/Step_0_ANN_Two_Result_ProcessA.csv'
Traceback (most recent call last):
  File "D:\StockPrediction\StockPrediction\\package\Step_1_CombineCSV.py", line 33, in <module>
    recordADF.to_csv(filePath+recordA, encoding='big5', index=False)
  File "C:\Users\Vivian\AppData\Roaming\Python\Python38\site-packages\pandas\core\generic.py", line 3170, in to_csv
    formatter.save()
  File "C:\Users\Vivian\AppData\Roaming\Python\Python38\site-packages\pandas\io\formats\csvs.py", line 185, in save
    f, handles = get_handle(
  File "C:\Users\Vivian\AppData\Roaming\Python\Python38\site-packages\pandas\io\common.py", line 493, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, errors=errors, newline="")
PermissionError: [Errno 13] Permission denied: './data/Step_0_ANN_Two_Result_ProcessA.csv'
Traceback (most recent call last):
  File "D:\StockPrediction\StockPrediction\\package\Step_1_CombineCSV.py", line 33, in <module>
    recordADF.to_csv(filePath+recordA, encoding='big5', index=False)
  File "C:\Users\Vivian\AppData\Roaming\Python\Python38\site-packages\pandas\core\generic.py", line 3170, in to_csv
    formatter.save()
  File "C:\Users\Vivian\AppData\Roaming\Python\Python38\site-packages\pandas\io\formats\csvs.py", line 185, in save
    f, handles = get_handle(
  File "C:\Users\Vivian\AppData\Roaming\Python\Python38\site-packages\pandas\io\common.py", line 493, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, errors=errors, newline="")
PermissionError: [Errno 13] Permission denied: './data/Step_0_ANN_Two_Result_ProcessA.csv'
Traceback (most recent call last):
  File "D:\StockPrediction\StockPrediction\\package\Step_1_CombineCSV.py", line 33, in <module>
    recordADF.to_csv(filePath+recordA, encoding='big5', index=False)
  File "C:\Users\Vivian\AppData\Roaming\Python\Python38\site-packages\pandas\core\generic.py", line 3170, in to_csv
    formatter.save()
  File "C:\Users\Vivian\AppData\Roaming\Python\Python38\site-packages\pandas\io\formats\csvs.py", line 185, in save
    f, handles = get_handle(
  File "C:\Users\Vivian\AppData\Roaming\Python\Python38\site-packages\pandas\io\common.py", line 493, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, errors=errors, newline="")
PermissionError: [Errno 13] Permission denied: './data/Step_0_ANN_Two_Result_ProcessA.csv'
Traceback (most recent call last):
  File "D:\StockPrediction\StockPrediction\\package\Step_1_CombineCSV.py", line 33, in <module>
    recordADF.to_csv(filePath+recordA, encoding='big5', index=False)
  File "C:\Users\Vivian\AppData\Roaming\Python\Python38\site-packages\pandas\core\generic.py", line 3170, in to_csv
    formatter.save()
  File "C:\Users\Vivian\AppData\Roaming\Python\Python38\site-packages\pandas\io\formats\csvs.py", line 185, in save
    f, handles = get_handle(
  File "C:\Users\Vivian\AppData\Roaming\Python\Python38\site-packages\pandas\io\common.py", line 493, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, errors=errors, newline="")
PermissionError: [Errno 13] Permission denied: './data/Step_0_ANN_Two_Result_ProcessA.csv'
Traceback (most recent call last):
  File "D:\StockPrediction\StockPrediction\\package\Step_1_CombineCSV.py", line 33, in <module>
    recordADF.to_csv(filePath+recordA, encoding='big5', index=False)
  File "C:\Users\Vivian\AppData\Roaming\Python\Python38\site-packages\pandas\core\generic.py", line 3170, in to_csv
    formatter.save()
  File "C:\Users\Vivian\AppData\Roaming\Python\Python38\site-packages\pandas\io\formats\csvs.py", line 185, in save
    f, handles = get_handle(
  File "C:\Users\Vivian\AppData\Roaming\Python\Python38\site-packages\pandas\io\common.py", line 493, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, errors=errors, newline="")
PermissionError: [Errno 13] Permission denied: './data/Step_0_ANN_Two_Result_ProcessA.csv'
INFO - 2022/06/22 22:39:51 -  End
INFO - 2022/06/22 22:50:00 -  End
INFO - 2022/06/22 23:20:00 -  End
INFO - 2022/06/22 23:50:00 -  End
